#ifndef SB_CONSTANTS
#define SB_CONSTANTS

enum sensor_orientation {
  SENSOR_ORIENTATION_N = 0,
  SENSOR_ORIENTATION_NW,
  SENSOR_ORIENTATION_W,
  SENSOR_ORIENTATION_SW,
  SENSOR_ORIENTATION_S,
  SENSOR_ORIENTATION_SE,
  SENSOR_ORIENTATION_E,
  SENSOR_ORIENTATION_NE
};

#endif
